name: TWS CD workflow

on:
  workflow_run:
    workflows: ["Ci Workflow"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            cd ~/Go-3tier-application-github-actions
            git pull origin main
            docker-compose pull
            docker-compose up -d
          timeout: 30s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 30s
